language: node_js

node_js:
  - 12

cache: yarn

before_install:
  - npm set //registry.npmjs.org/:_authToken $NPM_API_TOKEN

script:
  - yarn lint
  - yarn test

before_deploy:
  - yarn build

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  edge: true
  skip_cleanup: true
  on:
    tags: true